using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("DbWebApi")]
[assembly: AssemblyDescription("An universal Web API for invoking database stored procedures, transforming the results as JSON, BSON, JSONP, XML, CSV, Excel xlsx, or any text generated by Razor dynamic template. Please visit https://github.com/DataBooster/DbWebApi for detail.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Abel Cheng")]
[assembly: AssemblyProduct("DataBooster.DbWebApi")]
[assembly: AssemblyCopyright("Copyright © 2015-2017 Abel Cheng")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("63c461c8-27bf-485b-b042-c36119f2ee4b")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.2.12.2")]
[assembly: AssemblyFileVersion("1.2.12.2")]
[assembly: AssemblyInformationalVersion("1.2.12.2")]
