#
# Module manifest for module 'Send-Email'
#
# Generated by: Abel Cheng
#
# Generated on: 2017-03-01
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = 'Module.psd1'

# Version number of this module.
ModuleVersion = '1.0.0.1'

# ID used to uniquely identify this module
GUID = '33CC6B73-4FA6-4FA6-B1D2-A7E674009845'

# Author of this module
Author = 'Abel Cheng'

# Company or vendor of this module
CompanyName = 'https://github.com/DataBooster/'

# Copyright statement for this module
Copyright = '(c) 2017 Abel Cheng. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'A wrapper module of build-in Send-MailMessage cmdlet to take advantage of multiple SMTP servers (for redundant backup) in the enterprise intranet'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Send-Email.psm1')

# Functions to export from this module
FunctionsToExport = 'Send-Email'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{
	PSData = @{
		Tags = 'PSWebApi', 'PowerShell', 'WebApi', 'REST', 'Email', 'SMTP';
		ProjectUri = 'https://github.com/DataBooster/DbWebApi';
		LicenseUri = 'https://github.com/DataBooster/DbWebApi/blob/master/LICENSE';
	}
}

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/DataBooster/DbWebApi'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
